export default{
     certificateSubject:[
        {
            label:'幼儿园',
            value:0
        },
        {
            label:'小学全科',
            value:1
        },
        {
            label:'语文',
            value:2
        },
        {
            label:'数学',
            value:3
        },
        {
            label:'英语',
            value:4
        },
        {
            label:'物理',
            value:5
        },
        {
            label:'化学',
            value:6
        },
        {
            label:'生物',
            value:7
        },
        {
            label:'历史',
            value:8
        },

        {
            label:'地理',
            value:9
        },
        {
            label:'科学',
            value:10
        },
        {
            label:'思想品德',
            value:11
        },
        {
            label:'思想政治',
            value:12
        },
        {
            label:'心理健康教育',
            value:13
        },
        {
            label:'体育与健康',
            value:14
        },
        {
            label:'音乐',
            value:15
        },
        {
            label:'美术',
            value:16
        },
        {
            label:'信息技术',
            value:17
        },
        {
            label:'通用技术',
            value:18
        },
        {
            label:'体育',
            value:19
        },

        {
            label:'历史与社会',
            value:20
        },
        {
            label:'社会',
            value:21
        },
    ]
}