
    const options1= [
        {
            label:'985',
            value:'985'
        },
        {
            label:'211',
            value:'211'
        },
        {
            label:'一本',
            value:'一本'
        },
        {
            label:'二本A',
            value:'二本A'
        },
        {
            label:'二本B',
            value:'二本B'
        },
        {
            label:'三本',
            value:'三本'
        }
    ];
    const options2= [
        {
            label:'全部',
            value:''
        },
        {
            label:'本科',
            value:'本科'
        },
        {
            label:'硕士',
            value:'硕士'
        },
        {
            label:'博士及以上',
            value:'博士及以上'
        }
    ];
    const options3= [
        {
            label:'全部',
            value:''
        },
        {
            label:'有',
            value:'1'
        },
        {
            label:'无',
            value:'0'
        }
    ];
    const options4= [
        {
            label:'全部',
            value:''
        },
        {
            label:'未处理',
            value:'未处理'
        },
        {
            label:'通过',
            value:'PASS'
        },
        {
            label:'淘汰',
            value:'ELIMINATE'
        },
        {
            label:'分配失败',
            value:'ALLOCATION_FAILED'
        }
    ];
    const options5=[
        {
            label:'全部',
            value:''
        },
        {
            label:'已毕业',
            value:'1'
        },
        {
            label:'未毕业',
            value:'0'
        },
    ];
    const options6=[
        {
            label:'=',
            value:0
        },
        {
            label:'>',
            value:1
        },
        {
            label:'≥',
            value:2
        },
        {
            label:'<',
            value:-1
        },
        {
            label:'≤',
            value:-2
        }
    ];

    const options7=[
        {
            label:'学校不符合',
            value:'学校不符合'
        },
        {
            label:'学历不符合',
            value:'学历不符合'
        },
        {
            label:'无教师资格证',
            value:'无教师资格证'
        },
        {
            label:'未毕业',
            value:'未毕业'
        }
    ];

    const tableConfig=[
        {
            label:'姓名',
            prop:'name',

        },
        {
            label:'手机号',
            prop:'mobile'
        },
        {
            label:'年龄',
            prop:'age'
        },
        {
            label:'是否毕业',
            prop:'graduationName'
        },
        {
            label:'学历',
            prop:'eduName'
        },
        {
            label:'学校等级',
            prop:'schoolLevel'
        },
        {
            label:'学校',
            prop:'school',
            width:200
        },
        {
            label:'教资情况',
            prop:'certificateSituationName'
        },
        {
            label:'性别',
            prop:'sex'
        },
        {
            label:'应聘职位',
            prop:'applyJob',
            width:300
        },
        {
            label:'邮箱',
            prop:'email',
            width:200
        },
        {
            label:'投递渠道',
            prop:'emailDeliveryChannelName'
        },
        {
            label:'投递时间',
            prop:'sendTime',
            width:200
        },
        {
            label:'投递邮箱',
            prop:'emailAccount',
            width:200
        },
        {
            label:'投递邮箱专员姓名',
            prop:'emailAccountName'
        },
        {
            label:'跟进结果',
            prop:'followerResultName'
        },
        {
            label:'失败/淘汰原因',
            prop:'failedReason'
        }
    ]
    export {options1,options2,options3,options4,options5,options6,options7,tableConfig}
